"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { TRENDING_PATTERNS, getCurrentMonth, TrendingPattern } from "./data";
import PatternPreview from "./PatternPreview";

export default function TrendingPage() {
  const router = useRouter();
  const currentMonth = getCurrentMonth();
  const [patterns, setPatterns] = useState<TrendingPattern[]>(TRENDING_PATTERNS);
  const [isLive, setIsLive] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  // Check localStorage for cached trending data
  useEffect(() => {
    const cached = localStorage.getItem("trending_cache");
    if (cached) {
      try {
        const data = JSON.parse(cached);
        if (data.month === currentMonth && data.patterns?.length > 0) {
          setPatterns(data.patterns);
          setIsLive(true);
        }
      } catch { /* use static fallback */ }
    }
  }, [currentMonth]);

  const handleRefresh = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await fetch("/api/trending");
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || "Failed to fetch");
      }
      const data = await res.json();
      if (data.patterns?.length > 0) {
        setPatterns(data.patterns);
        setIsLive(true);
        localStorage.setItem("trending_cache", JSON.stringify(data));
      }
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to refresh trends");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleSelect = (prompt: string) => {
    sessionStorage.setItem("trending_prompt", prompt);
    router.push("/");
  };

  return (
    <div style={{ minHeight: "100vh", background: "var(--bg-primary)" }}>
      {/* Header */}
      <header style={{
        display: "flex", flexDirection: "column", alignItems: "center",
        padding: "24px 24px 0", background: "#FFF8F0",
        borderBottom: "1px solid var(--border)",
      }}>
        <a href="/" style={{
          fontFamily: "'Cormorant Garamond', Georgia, serif",
          fontSize: 28, fontWeight: 600, color: "var(--text-primary)",
          letterSpacing: "0.04em", textDecoration: "none", marginBottom: 6,
        }}>
          Dizzy with Excitement
        </a>
        <p style={{
          fontSize: 11, fontWeight: 500, letterSpacing: "0.15em",
          color: "var(--text-muted)", marginBottom: 16, textTransform: "uppercase",
        }}>
          AI Pattern Generator
        </p>
        <nav style={{ display: "flex", gap: 32, paddingBottom: 16 }}>
          <a href="/" style={{
            color: "var(--text-secondary)", textDecoration: "none",
            fontSize: 12, fontWeight: 500, letterSpacing: "0.12em",
          }}>
            GENERATOR
          </a>
          <span style={{
            color: "var(--text-primary)", fontSize: 12, fontWeight: 500,
            letterSpacing: "0.12em", borderBottom: "2px solid var(--text-primary)",
            paddingBottom: 2,
          }}>
            TRENDING {new Date().getFullYear()}
          </span>
          <a href="/saved" style={{
            color: "var(--text-secondary)", textDecoration: "none",
            fontSize: 12, fontWeight: 500, letterSpacing: "0.12em",
          }}>
            SAVED
          </a>
        </nav>
      </header>

      <main style={{ maxWidth: 960, margin: "0 auto", padding: "48px 24px 100px" }}>
        {/* Title */}
        <div style={{ textAlign: "center", marginBottom: 36 }}>
          <p style={{
            fontSize: 11, fontWeight: 500, letterSpacing: "0.2em",
            color: "var(--text-muted)", marginBottom: 12, textTransform: "uppercase",
          }}>
            {currentMonth}
          </p>
          <h1 style={{
            fontSize: 36, fontWeight: 500, color: "var(--text-primary)",
            marginBottom: 14, lineHeight: 1.2,
            fontFamily: "'Cormorant Garamond', Georgia, serif",
          }}>
            Trending Wallpapers
          </h1>
          <p style={{
            color: "var(--text-secondary)", fontSize: 15, lineHeight: 1.7,
            maxWidth: 560, margin: "0 auto",
          }}>
            {isLive
              ? "Fresh trends generated by AI based on current search data. Click any design to generate it."
              : "The most popular wallpaper patterns this month. Click any design to generate it instantly with AI."
            }
          </p>
          {isLive && (
            <span style={{
              display: "inline-block", marginTop: 10, padding: "4px 12px",
              background: "var(--accent)", color: "#fff",
              fontSize: 10, fontWeight: 600, letterSpacing: "0.1em",
              textTransform: "uppercase",
            }}>
              LIVE TRENDS
            </span>
          )}
        </div>

        {/* Refresh button */}
        <div style={{ textAlign: "center", marginBottom: 24 }}>
          <button
            onClick={handleRefresh}
            disabled={isLoading}
            style={{
              padding: "10px 24px", border: "none",
              background: isLoading ? "var(--bg-card)" : "var(--accent)",
              color: isLoading ? "var(--text-muted)" : "#fff",
              fontSize: 12, fontWeight: 600, letterSpacing: "0.1em",
              cursor: isLoading ? "not-allowed" : "pointer",
              textTransform: "uppercase",
            }}
          >
            {isLoading ? "REFRESHING..." : "REFRESH TRENDS"}
          </button>
        </div>

        {/* Grid */}
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
          gap: 20,
        }}>
          {patterns.map((pattern, index) => (
            <button
              key={pattern.id}
              onClick={() => handleSelect(pattern.prompt)}
              style={{
                textAlign: "left", border: "1px solid var(--border)",
                background: "#ffffff", cursor: "pointer",
                padding: 0, transition: "all 0.2s",
                display: "flex", flexDirection: "column",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = "var(--accent)";
                e.currentTarget.style.transform = "translateY(-2px)";
                e.currentTarget.style.boxShadow = "0 4px 12px rgba(0,0,0,0.08)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = "var(--border)";
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "none";
              }}
            >
              {/* Pattern preview */}
              <PatternPreview pattern={pattern} width={280} height={180} />

              {/* Content */}
              <div style={{ padding: "16px 20px", flex: 1 }}>
                <div style={{
                  display: "flex", justifyContent: "space-between",
                  alignItems: "center", marginBottom: 8,
                }}>
                  <span style={{
                    fontSize: 11, fontWeight: 700, letterSpacing: "0.1em",
                    color: "var(--accent)",
                  }}>
                    #{index + 1}
                  </span>
                  <span style={{
                    fontSize: 10, fontWeight: 500, letterSpacing: "0.12em",
                    color: "var(--text-muted)", textTransform: "uppercase",
                  }}>
                    {pattern.category}
                  </span>
                </div>

                <h3 style={{
                  fontSize: 18, fontWeight: 500, color: "var(--text-primary)",
                  marginBottom: 6, lineHeight: 1.3,
                  fontFamily: "'Cormorant Garamond', Georgia, serif",
                }}>
                  {pattern.title}
                </h3>

                <p style={{
                  fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5,
                  marginBottom: 12,
                }}>
                  {pattern.description}
                </p>

                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <div style={{
                    flex: 1, height: 4, background: "var(--border)",
                    borderRadius: 2, overflow: "hidden",
                  }}>
                    <div style={{
                      width: `${pattern.popularity}%`, height: "100%",
                      background: "var(--accent)", borderRadius: 2,
                    }} />
                  </div>
                  <span style={{
                    fontSize: 11, color: "var(--text-muted)", fontWeight: 500,
                    minWidth: 28,
                  }}>
                    {pattern.popularity}%
                  </span>
                </div>
              </div>

              <div style={{
                padding: "12px 20px", borderTop: "1px solid var(--border)",
                fontSize: 11, fontWeight: 600, letterSpacing: "0.1em",
                color: "var(--accent)", textTransform: "uppercase",
              }}>
                Generate This Pattern &rarr;
              </div>
            </button>
          ))}
        </div>
      </main>
    </div>
  );
}
